### ISSUE TITLE
WebSocket connection to 'ws://localhost:56739/signalr/connect? Failed during WebSocket handshake

### ISSUE THREAD

**Issue by nishrathi** [mdevilliers/SignalR.RabbitMq#41] opened 2015-11-07 04:40 UTC
![snap 2015-11-06 at 23 38 51](https://cloud.githubusercontent.com/assets/14582014/11013536/9465aefc-84df-11e5-8cf2-c1aeca518e7b.png)
WebSocket connection to 'ws://localhost:56739/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=fa61yB8k4JcZoMO%2F1iFhscu9Mtklkh6%2FZuX%2Bx1ONa161moMg2y%2Bype6u%2BZFhyrNc6JKZRrUDHXoYifHWc7po%2FOc%2FWK%2Be649oFYk01eoseN3LTFGZHG3p5GYARyNAPION&connectionData=%5B%7B%22name%22%3A%22chat%22%7D%5D&tid=2' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

**Comment by mdevilliers** [comment] 2015-11-07 10:24
Hey,

A few things to check -

1. Is the RabbitMQ plugin installed?
2. Are the connection details correct? 
3. Does you application work without using the scaleout bus?

Thanks,

Mark

**Comment by nishrathi** [comment] 2015-11-07 16:44
Hi Mark,

 1. RabbitMQ stamp plugin is installed.
 2. Connection details are the default ones i.e. localhost, guest, guest
 3. I was trying to run the example code and have no idea about the Scaleout bus 

FYI, i have latest RabbitMQ 3.5.6 and Erlang 18.1
![snap 2015-11-07 at 11 43 01](https://cloud.githubusercontent.com/assets/14582014/11016107/c62dc248-8544-11e5-8e1c-405c96e9787b.png)

**Comment by mdevilliers** [comment] 2015-11-07 17:45
The last plugin I did for RMQ 3.5.* is at 

https://github.com/mdevilliers/SignalR.RabbitMq/tree/master/rabbitmq-plugin/RabbitMQ_3_5/erlang_17

 Could you just double check that is the one you have installed? If it doesn't work we might have to build a plugin for that combination of RMQ and Erlang.

Thanks,

Mark

**Comment by nishrathi** [comment] 2015-11-07 18:14
oops,i think I installed the wrong plugin (https://github.com/mdevilliers/rabbitmq-stamp/tree/master/compiled/1.0.3/rabbitmq_3_3_1/erlang_17). 

Now i have updated with the one that you provided.
Websocket endpoint is still failing 
but the SSE endpoint is connected and the example is working now, So not sure if this is how it is supposed to work or the Websocket endpoint should also be working?

![snap 2015-11-07 at 13 08 41](https://cloud.githubusercontent.com/assets/14582014/11016494/4263a7e0-8551-11e5-8137-64b9ee2c2f38.png)

Thanks,
Nish

**Comment by mdevilliers** [comment] 2015-11-09 09:50
The web-socket endpoint should be working. I am afraid I have little to no experience with debugging issues with it.

Does the web-socket endpoint work when you don't use SignalR.RabbitMq?

**Comment by mdevilliers** [comment] 2015-11-17 20:33
Closing as I believe the problem is now no related to the plugin.

Please reopen if this isn't the case.

**Closed by mdevilliers** 2015-11-17 20:33 UTC
